### ISSUE TITLE
wrong link when attribute name is the same as type / class name

### ISSUE THREAD

**Issue by noname77** [rogerbarton/sphinx-csharp#6]
hi, i think i've found another issue which might be specific to the csharp domain since it allows for the attributes to have the same name as their types

example class definitions:
```
public class Foo
{
    public Foo() {}
}

public class Bar
{
    public Foo Foo;

    public Bar() {
        Foo = new Foo();
    }
}
```

the issue is that the link to `Foo` class from the type in `Bar`'s attribute documentation doesn't lead to the `Foo`'s documentation page, but to the `Foo` attribute / variable in the `Bar`'s documentation instead (see the title when hovering). doxygen handles this correctly

sphinx html render:
![image](https://user-images.githubusercontent.com/5903414/131874283-0ee79c2a-795b-4a6e-9d58-7221a534ac42.png)

i'd be happy to provide more details if necessary

**Comment by rogerbarton** [comment]
Yes, this issue belongs to sphinx-csharp. Specifically the `resolve_xref` fct https://github.com/rogerbarton/sphinx-csharp/blob/edaefa9772d47bd827b41a3e4a0e4d80054833f3/sphinx_csharp/csharp.py#L795.

I assume that you are getting:
```
WARNING: Ambiguous reference to Foo, potential matches: {...}
```
In which case, it will just take the first match. This problem only really occurs because we are trying to resolve `Foo` without knowing the full name `Namespace.Foo`, which is unique. Somehow this information is lost between the xml and shpinx-csharp.

**Comment by rogerbarton** [comment]
Can you try with `pip install git+https://github.com/rogerbarton/sphinx-csharp.git@dev`?

https://github.com/rogerbarton/sphinx-csharp/commit/5d06cdcfbcfce9c2cc5abe42cbe3533f765821cb should have fixed this. Although reference resolution is still far from optimal/exact.

**Comment by noname77** [comment]
thanks for sorting this out quickly again!

links to types with the same names as members for work as expected now
